package product;

import graphql.GraphQLClient;
import graphql.GraphQLQueryProductList;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import org.json.JSONException;

public class ProductList {
  public List<Product> products;

  public ProductList(List<Product> products) {
    this.products = products;
  }

  public static ProductList retrieveProducts(String url) {
    GraphQLClient client = new GraphQLClient(url);
    GraphQLQueryProductList query = new GraphQLQueryProductList();
    try {
      return client.executeQuery(query);
    } catch (IOException | InterruptedException | JSONException e) {
      // TODO: Handle this exception properly.
      throw new RuntimeException(e);
    }
  }

  // Overriding the equals and hashCode to make assertEquals() compare the objects by values,
  // not that they are the exact same object.
  // NOTE: These have been generated by IntelliJ IDEA.
  @Override
  public boolean equals(Object o) {
    if (o == null || getClass() != o.getClass()) return false;
    ProductList that = (ProductList) o;
    return Objects.equals(products, that.products);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(products);
  }
}
