package product;

import java.util.Objects;

public class Product {
  private int id;
  private String name;
  private double price;

  public Product(int id, String name, double price) {
    this.id = id;
    this.name = name;
    this.price = price;
  }

  public int getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public double getPrice() {
    return price;
  }

  // Overriding the equals and hashCode to make assertEquals() compare the objects by values,
  // not that they are the exact same object.
  // NOTE: These have been generated by IntelliJ IDEA.
  @Override
  public boolean equals(Object o) {
    if (o == null || getClass() != o.getClass()) return false;
    Product product = (Product) o;
    return id == product.id
        && Double.compare(price, product.price) == 0
        && Objects.equals(name, product.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, price);
  }
}
