name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Test with Gradle
        run: ./gradlew test
